// <auto-generated />
using System;
using EntityFrameworkCoreLearning.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntityFrameworkCoreLearning.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookEntityGenreEntity", b =>
                {
                    b.Property<Guid>("BooksId")
                        .HasColumnType("uuid")
                        .HasColumnName("books_id");

                    b.Property<Guid>("GenresId")
                        .HasColumnType("uuid")
                        .HasColumnName("genres_id");

                    b.HasKey("BooksId", "GenresId")
                        .HasName("pk_book_entity_genre_entity");

                    b.HasIndex("GenresId")
                        .HasDatabaseName("ix_book_entity_genre_entity_genres_id");

                    b.ToTable("book_entity_genre_entity", (string)null);
                });

            modelBuilder.Entity("EntityFrameworkCoreLearning.Data.Models.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<Guid>("PublisherEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("publisher_entity_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.HasIndex("PublisherEntityId")
                        .HasDatabaseName("ix_books_publisher_entity_id");

                    b.ToTable("books", null, t =>
                        {
                            t.HasCheckConstraint("CK_Book_Year_ValidRange", "year >= 1600 AND year <= EXTRACT(YEAR FROM NOW())");
                        });
                });

            modelBuilder.Entity("EntityFrameworkCoreLearning.Data.Models.GenreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("EntityFrameworkCoreLearning.Data.Models.PublisherEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_publishers");

                    b.ToTable("publishers", (string)null);
                });

            modelBuilder.Entity("BookEntityGenreEntity", b =>
                {
                    b.HasOne("EntityFrameworkCoreLearning.Data.Models.BookEntity", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_entity_genre_entity_books_books_id");

                    b.HasOne("EntityFrameworkCoreLearning.Data.Models.GenreEntity", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_entity_genre_entity_genres_genres_id");
                });

            modelBuilder.Entity("EntityFrameworkCoreLearning.Data.Models.BookEntity", b =>
                {
                    b.HasOne("EntityFrameworkCoreLearning.Data.Models.PublisherEntity", "PublisherEntity")
                        .WithMany("Books")
                        .HasForeignKey("PublisherEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_books_publishers_publisher_entity_id");

                    b.Navigation("PublisherEntity");
                });

            modelBuilder.Entity("EntityFrameworkCoreLearning.Data.Models.PublisherEntity", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
